# Generated by Django 3.2.16 on 2022-12-29 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, choices=[('Build Business Presence', 'Build Business Presence'), ('StartPlus+', 'StartPlus+'), ('Digital-X for Business', 'Digital-X for Business'), ('Be Digital for School', 'Be Digital for School'), ('Learnincreation Business Profile', 'Learnincreation Business Profile'), ('Digital Marketing ', 'Digital Marketing'), ('Social Media Marketing', 'Social Media Marketing'), ('Create Learnincreation Shop', 'Create Learnincreation Shop')], max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(help_text='Enter Date month/date/year')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.FileField(blank=True, null=True, upload_to='media')),
                ('content', models.TextField(blank=True, null=True)),
                ('content_addition', models.TextField(blank=True, null=True)),
                ('highlight', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('item', models.CharField(blank=True, choices=[('Build Business Presence', 'Build Business Presence'), ('StartPlus+', 'StartPlus+'), ('Digital-X for Business', 'Digital-X for Business'), ('Be Digital for School', 'Be Digital for School'), ('Learnincreation Business Profile', 'Learnincreation Business Profile'), ('Digital Marketing ', 'Digital Marketing'), ('Social Media Marketing', 'Social Media Marketing'), ('Create Learnincreation Shop', 'Create Learnincreation Shop')], max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('payment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
