# Generated by Django 3.2.16 on 2022-12-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='wallet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='item',
            field=models.CharField(blank=True, choices=[('Build Business Presence', 'Build Business Presence'), ('StartPlus+', 'StartPlus+'), ('E-Books', 'E-Books'), ('Digital-X for Business', 'Digital-X for Business'), ('Be Digital for School', 'Be Digital for School'), ('Learnincreation Business Profile', 'Learnincreation Business Profile'), ('Digital Marketing ', 'Digital Marketing'), ('Marketing\tContent\tDesign', 'Marketing\tContent\tDesign'), ('Social Media Marketing', 'Social Media Marketing'), ('Create Learnincreation Shop', 'Create Learnincreation Shop')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='item',
            field=models.CharField(blank=True, choices=[('Build Business Presence', 'Build Business Presence'), ('StartPlus+', 'StartPlus+'), ('E-Books', 'E-Books'), ('Digital-X for Business', 'Digital-X for Business'), ('Be Digital for School', 'Be Digital for School'), ('Learnincreation Business Profile', 'Learnincreation Business Profile'), ('Digital Marketing ', 'Digital Marketing'), ('Marketing\tContent\tDesign', 'Marketing\tContent\tDesign'), ('Social Media Marketing', 'Social Media Marketing'), ('Create Learnincreation Shop', 'Create Learnincreation Shop')], max_length=50, null=True),
        ),
    ]
