# Generated by Django 3.2.16 on 2022-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20221229_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='total',
            field=models.TextField(blank=True, null=True),
        ),
    ]
