# Generated by Django 3.2.16 on 2022-12-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20221229_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='total',
        ),
    ]
