# Generated by Django 3.2.16 on 2022-12-29 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', help_text='Upload Your Picture', null=True, upload_to='profiles_pics')),
                ('signature_image', models.ImageField(blank=True, help_text='Upload Your signature image', null=True, upload_to='sign_pics')),
                ('domicile', models.CharField(blank=True, choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunanchal Pradesh'), ('Assam', 'Assam '), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerela', 'Kerela'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh '), ('Maharastra', 'Maharastra '), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', ' Odisha'), ('Punjab', ' Punjab'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Naidu', 'Tamil Naidu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], help_text='Choose Your Domicile', max_length=30, null=True)),
                ('aadhar', models.CharField(help_text='Enter Aadhar Id Number', max_length=17)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Choose Your Gender', max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, help_text='Proud To Say Indian', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Enter Your Mobile number', max_length=10, null=True)),
                ('house_no', models.CharField(blank=True, help_text='Enter House / Flat Number / Colony / Ward No. ', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Enter Your Address Details', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter Your City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='Enter Your State', max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Enter Your Postal Code ** PIN Code', max_length=6, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB- ', 'AB-'), ('O+', 'O+'), ('O- ', 'O-')], help_text='Choose Your Blood Group', max_length=5, null=True)),
                ('skill', models.CharField(blank=True, help_text='About Your Skills - Things you do greatly', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
