# Generated by Django 3.2.16 on 2022-12-29 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('to_the_department', models.CharField(blank=True, choices=[('Sales & Services', 'Sales & Services'), ('Account', 'Account'), ('Tech Support', 'Tech Support'), ('Build your Business', 'Build your Business'), ('Customer Executive', 'Customer Executive')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
